server:
  port: 9090

spring:
  devtools:
    livereload:
      port: 35731
  cloud:
    gateway:
      routes:
        - id: planes
          uri: lb://planes
          predicates:
            - Path=/planes/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    healthcheck:
      enabled: true

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
