server:
  port: 8081

spring:
  devtools:
    livereload:
      port: 35732
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    mongodb:
      database: airline

eureka:
  client:
    healthcheck:
      enabled: true

logging:
  level:
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
          - metrics
          - prometheus
